# Generated by Django 4.0.5 on 2022-08-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='Categories',
            new_name='name',
        ),
        migrations.AddField(
            model_name='founditems',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lostandfoundapp.categories'),
        ),
    ]
