# Generated by Django 4.0.5 on 2022-08-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundapp', '0002_rename_categories_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lostandfoundapp.categories'),
        ),
    ]
