# Generated by Django 4.0.5 on 2022-08-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundapp', '0003_alter_founditems_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
