# Generated by Django 4.0.5 on 2022-08-15 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundapp', '0005_alter_founditems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditems',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 8, 15, 18, 11, 14, 303058, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
