# Generated by Django 4.0.5 on 2022-08-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundapp', '0006_founditems_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='textfield',
            field=models.TextField(max_length=400),
        ),
    ]
