# Generated by Django 4.0.5 on 2022-08-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundapp', '0007_alter_founditems_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditems',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
