# Generated by Django 4.0.5 on 2022-08-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfoundapp', '0008_founditems_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditems',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
